### ISSUE TITLE
In plugin, there are two sections for Twitter full URL, which seems the same.

### ISSUE THREAD

**Issue by gurjyot** [q2amarket/FlatBox#5]
If there is any difference between these two Twitter Full URL sections then what's that, or are they coppied by mistake. 

![flatbox](https://cloud.githubusercontent.com/assets/6462850/4875228/bfcf5c94-628c-11e4-9662-7f8f0e8e6cbd.png)

**Comment by q2amarket** [comment]
Done with new updates
